[project]
name = "less"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "peft==0.7.1",
    "setuptools>=80.9.0",
    "torch>=2.9.0",
    "tracker>=0.1.1",
    "transformers==4.36.2",
]
